### ISSUE TITLE
Heap space issues on import

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper-Plugins/mdm-plugin-database-postgresql#13]
When calculating enumerations / summary metadata:

```
2022-04-13 20:59:00,351 [080-exec-3] ERROR o.g.web.errors.GrailsExceptionResolver   : OutOfMemoryError occurred when processing request: [POST] /api/dataModels/import/uk.ac.ox.softeng.maurodatamapper.plugins.database.postgres/PostgresDatabaseDataModelImporterProviderService/6.0.0 - parameters:
folderId: ed90f3db-b4ef-4beb-a224-7fc3fa4c3ce2
modelName: 
dataModelNameSuffix: 
importAsNewBranchModelVersion: false
importAsNewDocumentationVersion: false
propagateFromPreviousVersion: false
finalised: false
schemaNames: 
databaseHost: localhost
databaseUsername: maurodatamapper
databasePassword: MauroDataMapper1234
databasePort: 
databaseSSL: false
newBranchName: 
databaseNames: maurodatamapper
organisation: 
author: 
description: 
maxEnumerations: 20
detectEnumerations: true
calculateSummaryMetadata: false
sampleThreshold: 
samplePercent: 
Java heap space. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by olliefreeman** [comment]
V6 has issues due to the way it performs sampling, pls try the latest develop branch 6.1.0-SNAPSHOT as this probably won’t have the same issues

**Comment by jamesrwelch** [comment]
No joy, sadly.  Running against Mauro's own database.
